// local custom imports
import { FONT_FAMILY } from "@/constants";
import { FontSizeFunction } from "@/theme/typography/typography.interface";

export const Others = (ResponsiveFontSizes: FontSizeFunction) => {
  return {
    bodyBigReg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 15, sm: 15, md: 16, lg: 16, xl: 18 }),
    },
    bodyBigSemi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 15, sm: 15, md: 16, lg: 17, xl: 18 }),
    },
    bodyBigBold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 15, sm: 15, md: 16, lg: 17, xl: 18 }),
    },
    body1Reg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 14, sm: 15, md: 14, lg: 16, xl: 16 }),
    },
    body1Semi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 14, sm: 15, md: 16, lg: 18, xl: 18 }),
    },
    body1Bold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 14, sm: 15, md: 14, lg: 16, xl: 16 }),
    },
    body1Bold3: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 14, sm: 15, md: 14, lg: 16, xl: 16 }),
    },
    body1Bold2: {
      fontFamily: FONT_FAMILY,
      fontWeight: 500,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 14, sm: 15, md: 14, lg: 16, xl: 16 }),
    },
    subtitle2Reg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    subtitle2Semi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      color: "neutral.main",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    subtitle2Bold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    buttonReg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    buttonSemi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    buttonBold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    body2Reg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    body2Semi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    body2Bold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 12, sm: 12, md: 13, lg: 14, xl: 14 }),
    },
    captionReg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 11, sm: 12, md: 12, lg: 12, xl: 12 }),
    },
    captionSemi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 11, sm: 12, md: 12, lg: 12, xl: 12 }),
    },
    captionBold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 11, sm: 12, md: 12, lg: 12, xl: 12 }),
    },
    overlineReg: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 10, sm: 10, md: 10, lg: 10, xl: 11 }),
    },
    overlineSemi: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "30px",
      letterSpacing: "0.15px",
      ...ResponsiveFontSizes({ xs: 10, sm: 10, md: 10, lg: 10, xl: 11 }),
    },
    overlineBold: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      lineHeight: "16px",
      letterSpacing: "0.4px",
      ...ResponsiveFontSizes({ xs: 8, sm: 9, md: 9, lg: 10, xl: 10 }),
    },
    overlineBold3: {
      fontFamily: FONT_FAMILY,
      fontWeight: 700,
      lineHeight: "16px",
      letterSpacing: "0.4px",
      ...ResponsiveFontSizes({ xs: 8, sm: 9, md: 9, lg: 10, xl: 10 }),
    },
    overlineBold2: {
      fontFamily: FONT_FAMILY,
      fontWeight: 500,
      lineHeight: "16px",
      letterSpacing: "0.4px",
      ...ResponsiveFontSizes({ xs: 8, sm: 9, md: 9, lg: 10, xl: 10 }),
    },
    smallText: {
      fontFamily: FONT_FAMILY,
      fontWeight: 400,
      lineHeight: "7px",
      letterSpacing: "0.4px",
      ...ResponsiveFontSizes({ xs: 6, sm: 7, md: 8, lg: 8, xl: 8 }),
    },
    smallText2: {
      fontFamily: FONT_FAMILY,
      fontWeight: 600,
      // lineHeight: "5px",
      letterSpacing: "0.4px",
      ...ResponsiveFontSizes({ xs: 6, sm: 7, md: 8, lg: 8, xl: 8 }),
    },
  };
};
